import RedUnit from 'https://redcamel.github.io/RedUnit/dist/index.js'

RedUnit.pageLoader('RedGPU', [
	{title: 'initialize', src: './initialize'},
	{title: 'object3DContainer', src: './object3DContainer'},
	{title: 'test1', src: './test'},
	{title: 'formatBytes', src: './util/formatBytes'},
	{title: 'matToEuler', src: './util/matToEuler'},
	{title: 'quaternionToRotationMat4', src: './util/quaternionToRotationMat4'},
	{title: 'file', src: './util/file'},
	{title: 'convertColor', src: './color/convertColor'},
	{title: 'colorRgb', src: './color/colorRgb'},
	{title: 'colorRgba', src: './color/colorRgba'},
	{title: 'runtimeChecker', src: './runtimeChecker'},
	{title: 'uuid', src: './util/uuid'},
	{title: 'absoluteURL', src: './util/absoluteURL'},
	{title: 'sortTransparentObjects', src: './util/sortTransparentObjects'},
	{title: 'calculateNormals', src: './util/calculateNormals'},
	{title: 'calculateTangents', src: './util/calculateTangents'},
	{title: 'computeViewFrustumPlanes', src: './util/computeViewFrustumPlanes'},
	{title: 'coordinates', src: './util/coordinates'},
	{title: 'textureUtils', src: './util/texture'},
	{title: 'boundUtils', src: './util/bound'},
	{title: 'errorUtils', src: './util/error'},
	{title: 'copyGPUBuffer', src: './util/copyGPUBuffer'},
])
