import * as RedGPU from "../../../../dist/index.js?t=1784264152422";
import RedGPUExampleHelper from "../../../exampleHelper/dist/index.js?t=1784264152422";

/**
 * [KO] Directional Light 그림자 예제
 * [EN] Directional Light Shadow example
 *
 * [KO] Directional Light에 의해 발생하는 실시간 그림자 효과와 설정을 보여줍니다.
 * [EN] Demonstrates real-time shadow effects and configurations generated by Directional Light.
 */

const canvas = document.createElement("canvas");
document.body.appendChild(canvas);

RedGPU.init(
    canvas,
    (redGPUContext) => {
        // 1. 카메라 및 뷰 설정
        const controller = new RedGPU.Camera.OrbitController(redGPUContext);
        controller.tilt = -15;
        controller.distance = 30;

        const scene = new RedGPU.Display.Scene();
        const view = new RedGPU.Display.View3D(redGPUContext, scene, controller);
        redGPUContext.addView(view);

        // 2. 조명 설정
        // [KO] 그림자를 생성할 방향성 조명을 추가합니다.
        // [EN] Add a directional light that will generate shadows.
        const directionalLight = new RedGPU.Light.DirectionalLight();
        scene.lightManager.addDirectionalLight(directionalLight);

        // 3. 스카이박스 설정
        view.skybox = createSkybox(redGPUContext);

        // 4. 무작위 객체 생성
        addRandomMeshes(redGPUContext, scene);

        // 5. 애니메이션 렌더 루프 및 시작
        const renderer = new RedGPU.Renderer();
        renderer.start(redGPUContext, (time) => {
            // 생성된 무작위 메시들의 애니메이션 처리 (첫 번째 자식인 바닥 제외)
            let i = scene.numChildren;
            while (i--) {
                if (i === 0) continue; // 바닥 메시 제외
                const mesh = scene.children[i];
                mesh.rotationX += 1.5;
                mesh.rotationY += 1.5;
                mesh.rotationZ += 1.5;
                mesh.y += Math.sin(time / 1000 + i * 10) / 10;
            }
        });

        // 6. 테스트 GUI 설정
        renderTestPane(redGPUContext, scene);
    },
    (failReason) => {
        console.error("Initialization failed:", failReason);
        const errorMessage = document.createElement("div");
        errorMessage.innerHTML = failReason;
        document.body.appendChild(errorMessage);
    }
);

/**
 * [KO] 스카이박스를 생성합니다.
 * [EN] Creates a skybox.
 */
const createSkybox = (redGPUContext) => {
    const skyboxImagePaths = [
        "../../../assets/skybox/px.jpg",
        "../../../assets/skybox/nx.jpg",
        "../../../assets/skybox/py.jpg",
        "../../../assets/skybox/ny.jpg",
        "../../../assets/skybox/pz.jpg",
        "../../../assets/skybox/nz.jpg",
    ];

    const cubeTexture = new RedGPU.Resource.CubeTexture(redGPUContext, skyboxImagePaths);
    return new RedGPU.Display.SkyBox(redGPUContext, cubeTexture);
};

/**
 * [KO] 무작위 메시들을 씬에 추가합니다.
 * [EN] Adds random meshes to the scene.
 */
const addRandomMeshes = (redGPUContext, scene) => {
    const geometries = [
        new RedGPU.Primitive.Sphere(redGPUContext, 2, 16, 16),
        new RedGPU.Primitive.Box(redGPUContext, 3, 3, 3),
        new RedGPU.Primitive.Cylinder(redGPUContext, 2, 2, 6, 16),
        new RedGPU.Primitive.Torus(redGPUContext, 1.5, 0.5, 16, 32),
        new RedGPU.Primitive.TorusKnot(redGPUContext, 0.5, 0.2, 128, 64, 2, 3)
    ];

    // 바닥 메시 생성 (그림자를 받음)
    const ground = new RedGPU.Display.Mesh(
        redGPUContext,
        new RedGPU.Primitive.Ground(redGPUContext),
        new RedGPU.Material.PhongMaterial(redGPUContext, '#ff0000')
    );
    ground.setScale(200);
    ground.receiveShadow = true;
    scene.addChild(ground);

    // 500개의 무작위 메시 생성
    for (let i = 0; i < 500; i++) {
        const geometry = geometries[Math.floor(Math.random() * geometries.length)];
        const material = new RedGPU.Material.PhongMaterial(redGPUContext, getRandomHexValue());

        const mesh = new RedGPU.Display.Mesh(redGPUContext, geometry, material);
        mesh.setScale(Math.max(Math.random() * 1.5, 0.5));
        mesh.setPosition(
            Math.random() * 150 - 75,
            Math.random() * 3 - 1.5,
            Math.random() * 150 - 75
        );
        mesh.rotationX = Math.random() * 360;
        mesh.rotationY = Math.random() * 360;
        mesh.rotationZ = Math.random() * 360;

        // 그림자 생성 설정
        mesh.castShadow = true;

        scene.addChild(mesh);
    }
};

/**
 * [KO] 무작위 16진수 색상 값을 반환합니다.
 * [EN] Returns a random hex color value.
 */
const getRandomHexValue = () => {
    const randomColor = Math.floor(Math.random() * 0xffffff);
    return `#${randomColor.toString(16).padStart(6, "0")}`;
};

/**
 * [KO] 테스트용 GUI를 렌더링합니다.
 * [EN] Renders the GUI for testing.
 */
const renderTestPane = (redGPUContext, scene) => {
    new RedGPUExampleHelper(redGPUContext, {
        gui: (pane) => {
            const {shadowManager} = scene;
            const {directionalShadowManager} = shadowManager;

            const folder = pane.addFolder({title: 'Directional Shadow', expanded: true});
            folder.addBinding(directionalShadowManager, 'shadowDepthTextureSize', {
                min: 128,
                max: 4096,
                step: 1,
                label: 'Texture Size'
            });
            folder.addBinding(directionalShadowManager, 'strength', {
                min: 0.0,
                max: 1.0,
                step: 0.01,
                label: 'Shadow Strength'
            });
            folder.addBinding(directionalShadowManager, 'filterScale', {
                min: 0.0,
                max: 15.0,
                step: 0.1,
                label: 'Filter Scale'
            });
        }
    });
};
