export const LANDSCAPE_DEBUG_MODE = {
    NONE: 0,
    FINAL_NORMAL: 1,
    MACRO_NORMAL: 2,
    ALBEDO: 3,
    SPLAT_WEIGHTS: 4,
    ROUGHNESS: 5,
    AMBIENT_OCCLUSION: 6,
    HEIGHTMAP_SHADOW_MASK: 7,
    CSM_SHADOW_MASK: 8,
    TOTAL_SHADOW_VISIBILITY: 9,
    ELEVATION_HEATMAP: 10,
    LOD_LEVEL: 11
} as const;

export type LANDSCAPE_DEBUG_MODE = typeof LANDSCAPE_DEBUG_MODE[keyof typeof LANDSCAPE_DEBUG_MODE];
Object.freeze(LANDSCAPE_DEBUG_MODE);
