import createUUID from "../utils/uuid/createUUID";
import InstanceIdGenerator from "../utils/uuid/InstanceIdGenerator";

/**
 * [KO] RedGPU의 모든 엔진 객체가 상속받는 최상위 추상 클래스입니다.
 * [EN] The top-level abstract class inherited by all engine objects in RedGPU.
 *
 * [KO] 모든 객체에 공통적으로 필요한 고유 식별자(UUID), 인스턴스 이름, 인스턴스 ID 관리 기능을 제공합니다.
 * [EN] Provides unique identifier (UUID), instance name, and instance ID management functions commonly required for all objects.
 *
 * @category Core
 */
abstract class BaseObject {
    /**
     * [KO] 클래스별 인스턴스 순번 ID
     * [EN] Instance sequence ID per class
     */
    readonly instanceId: number;
    /**
     * [KO] 객체의 고유 식별자 (UUID)
     * [EN] Universally Unique Identifier (UUID) of the object
     */
    #uuid: string = createUUID();
    /**
     * [KO] 객체의 이름
     * [EN] Name of the object
     */
    #name: string = '';

    /**
     * [KO] BaseObject 생성자입니다. (추상 클래스로 직접 인스턴스 생성은 불가합니다)
     * [EN] BaseObject constructor. (Abstract class, cannot be instantiated directly)
     */
    protected constructor() {
        this.instanceId = InstanceIdGenerator.getNextId(this.constructor);
    }

    /**
     * [KO] 객체의 고유 식별자(UUID)를 반환합니다.
     * [EN] Returns the universally unique identifier (UUID) of the object.
     *
     * @returns
     * [KO] UUID 문자열
     * [EN] UUID string
     */
    get uuid(): string {
        return this.#uuid;
    }

    /**
     * [KO] 객체의 이름을 반환합니다. 설정된 이름이 없으면 클래스명과 인스턴스 ID를 조합하여 자동으로 생성합니다.
     * [EN] Returns the name of the object. If no name is set, it is automatically generated by combining the class name and instance ID.
     *
     * @returns
     * [KO] 객체 이름
     * [EN] Name of the object
     */
    get name(): string {
        return this.#name || `${this.constructor.name} Instance ${this.instanceId}`;
    }

    /**
     * [KO] 객체의 이름을 설정합니다.
     * [EN] Sets the name of the object.
     *
     * @param value -
     * [KO] 설정할 객체 이름
     * [EN] Name of the object to set
     */
    set name(value: string) {
        this.#name = value;
    }
}

Object.freeze(BaseObject);
export default BaseObject;
