import createUUID from "../utils/uuid/createUUID";
import InstanceIdGenerator from "../utils/uuid/InstanceIdGenerator";

/**
 * [KO] RedGPU의 모든 엔진 객체가 상속받는 최상위 추상 클래스입니다.
 * [EN] The top-level abstract class inherited by all engine objects in RedGPU.
 *
 * [KO] 모든 객체에 공통적으로 필요한 고유 식별자(UUID), 인스턴스 이름, 인스턴스 ID 관리 기능을 제공합니다.
 * [EN] Provides unique identifier (UUID), instance name, and instance ID management functions commonly required for all objects.
 *
 * @category Core
 */
abstract class BaseObject {
    /**
     * [KO] 객체의 고유 식별자 (UUID)
     * [EN] Universally Unique Identifier (UUID) of the object
     */
    #uuid: string = createUUID();
    /**
     * [KO] 객체의 이름
     * [EN] Name of the object
     */
    #name: string = '';
    /**
     * [KO] 클래스별 인스턴스 순번 ID
     * [EN] Instance sequence ID per class
     */
    #instanceId: number;

    protected constructor() {

    }

    /**
     * [KO] 객체의 UUID를 반환합니다.
     * [EN] Returns the UUID of the object.
     */
    get uuid(): string {
        return this.#uuid;
    }

    /**
     * [KO] 객체의 이름을 반환합니다. 설정된 이름이 없으면 클래스명과 인스턴스 ID를 조합하여 자동으로 생성합니다.
     * [EN] Returns the name of the object. If no name is set, it is automatically generated by combining the class name and instance ID.
     */
    get name(): string {
        if (!this.#instanceId) this.#instanceId = InstanceIdGenerator.getNextId(this.constructor);
        return this.#name || `${this.constructor.name} Instance ${this.#instanceId}`;
    }

    /**
     * [KO] 객체의 이름을 설정합니다.
     * [EN] Sets the name of the object.
     */
    set name(value: string) {
        this.#name = value;
    }
}

Object.freeze(BaseObject);
export default BaseObject;
